{
 "title": "范围内机器和产量统计",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "server", "label": "服务器", "query": { "query": "label_values(url)" } },
   {
    "name": "session",
    "label": "会话",
    "query": {
     "query": "label_values({url=\"$server\"},session_name)"
    }
   },
   { "name": "xmin", "label": "x 最小值", "query": "-3750" },
   { "name": "xmax", "label": "x 最大值", "query": "3750" },
   { "name": "ymax", "label": "y 最大值", "query": "4910" },
   { "name": "ymin", "label": "y 最小值", "query": "-3750" }
  ]
 },
 "panels": [
  {
   "title": "当前实际生产量",
   "type": "table",
   "description": "选定时间段内的当前平均生产和消费情况（生产为正，消费为负）",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH\n  CombinedData AS (\n      SELECT metric, DATA\n      FROM CACHE\n      WHERE metric IN ('generators', 'factory', 'extractor')\n      AND (DATA -> 'location' ->> 'x') :: NUMERIC BETWEEN ($xmin * 100)\n      AND ($xmax * 100)\n      AND (DATA -> 'location' ->> 'y') :: NUMERIC BETWEEN ($ymin * 100)\n      AND ($ymax * 100)\n      AND url = '$server'\n      AND session_name = '$session'\n  ),\nconsumption AS (\n  SELECT\n    fi.item ->> 'Name' AS NAME,\n    ROUND(SUM(CASE WHEN fi.item ->> 'CurrentConsumed' ~ '^\\-?\\d+(\\.\\d+)?$' THEN (fi.item ->> 'CurrentConsumed') :: NUMERIC ELSE 0 END), 3) AS rate\n  FROM\n    CombinedData\n    CROSS JOIN LATERAL jsonb_array_elements (DATA -> 'ingredients') AS fi (item)\n  WHERE\n    metric IN ('factory', 'extractor')\n    AND fi.item ->> 'Name' IS NOT NULL\n    AND fi.item ->> 'Name' != 'Unassigned'\n  GROUP BY\n    1\n),\nproduction AS (\n  SELECT\n    fi.item ->> 'Name' AS NAME,\n    ROUND(SUM(CASE WHEN fi.item ->> 'CurrentProd' ~ '^\\-?\\d+(\\.\\d+)?$' THEN (fi.item ->> 'CurrentProd') :: NUMERIC ELSE 0 END), 3) AS rate\n  FROM\n    CombinedData\n    CROSS JOIN LATERAL jsonb_array_elements (DATA -> 'production') AS fi (item)\n  WHERE\n    metric IN ('factory', 'extractor')\n    AND fi.item ->> 'Name' IS NOT NULL\n    AND fi.item ->> 'Name' != 'Unassigned'\n  GROUP BY\n    1\n),\n  CurrentPotential AS (\n    SELECT\n      fi.item ->> 'Name' AS NAME,\n      ROUND((CombinedData.DATA ->> 'CurrentPotential') :: NUMERIC / 100.0, -- 保持 NUMERIC 类型\n        1) AS current_potential\n    FROM\n      CombinedData\n      CROSS JOIN LATERAL jsonb_array_elements (DATA -> 'FuelInventory') AS fi (item)\n    WHERE\n      metric = 'generators'\n      AND fi.item ->> 'Name' IS NOT NULL\n  ),\n itemcost AS (\n    SELECT item_name AS NAME, COST :: NUMERIC -- 显式转换为 NUMERIC\n    FROM item_data\n   ),\n fadianji AS(\n   SELECT COALESCE\n      (p.NAME, i.NAME) AS NAME,\n      ROUND(\n        CASE\n          WHEN SUM(COALESCE (p.current_potential, 0) * COALESCE (i.COST, 0)) IS NOT NULL THEN\n            CAST (\n              SUM(COALESCE (p.current_potential, 0) * COALESCE (i.COST, 0)) AS NUMERIC -- 显式转换为 NUMERIC\n            )\n          ELSE\n            0\n        END,\n        1\n      ) AS dangqianxiaohao\n  FROM CurrentPotential p LEFT JOIN itemcost i USING (NAME)\n  WHERE p.NAME = i.NAME\n  GROUP BY\n    1\n)\nSELECT COALESCE\n  (P.NAME, C.NAME,f.NAME) AS \"物品\",\n  ROUND(COALESCE (P.rate, 0),1) AS \"当前生产量\",\n  ROUND(COALESCE (f.dangqianxiaohao, 0) + COALESCE (C.rate, 0), 1) AS \"当前消耗量\",\n  ROUND(COALESCE (P.rate, 0),1) - ROUND(COALESCE (f.dangqianxiaohao, 0) + COALESCE (C.rate, 0), 1) AS \"当前盈余\"\nFROM\n  production P\n  FULL OUTER JOIN consumption C USING (NAME)\n  FULL OUTER JOIN fadianji f USING (NAME)\nORDER BY\n  \"当前盈余\" ASC,\n  \"当前消耗量\""
    }
   ]
  },
  {
   "title": "理论最大产量",
   "type": "table",
   "description": "最大理论生产量-最大理论消耗量",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH\n  CombinedData AS (\n      SELECT metric, DATA\n      FROM CACHE\n      WHERE metric IN ('generators', 'factory', 'extractor')\n      AND (DATA -> 'location' ->> 'x') :: NUMERIC BETWEEN ($xmin * 100)\n      AND ($xmax * 100)\n      AND (DATA -> 'location' ->> 'y') :: NUMERIC BETWEEN ($ymin * 100)\n      AND ($ymax * 100)\n      AND url = '$server'\n      AND session_name = '$session'\n  ),\nconsumption AS (\n  SELECT\n    fi.item ->> 'Name' AS NAME,\n    ROUND(SUM(CASE WHEN fi.item ->> 'MaxConsumed' ~ '^\\-?\\d+(\\.\\d+)?$' THEN (fi.item ->> 'MaxConsumed') :: NUMERIC ELSE 0 END), 3) AS rate\n  FROM\n    CombinedData\n    CROSS JOIN LATERAL jsonb_array_elements (DATA -> 'ingredients') AS fi (item)\n  WHERE\n    metric IN ('factory', 'extractor')\n    AND fi.item ->> 'Name' IS NOT NULL\n    AND fi.item ->> 'Name' != 'Unassigned'\n  GROUP BY\n    1\n),\nproduction AS (\n  SELECT\n    fi.item ->> 'Name' AS NAME,\n    ROUND(SUM(CASE WHEN fi.item ->> 'MaxProd' ~ '^\\-?\\d+(\\.\\d+)?$' THEN (fi.item ->> 'MaxProd') :: NUMERIC ELSE 0 END), 3) AS rate\n  FROM\n    CombinedData\n    CROSS JOIN LATERAL jsonb_array_elements (DATA -> 'production') AS fi (item)\n  WHERE\n    metric IN ('factory', 'extractor')\n    AND fi.item ->> 'Name' IS NOT NULL\n    AND fi.item ->> 'Name' != 'Unassigned'\n  GROUP BY\n    1\n),\n  CurrentPotential AS (\n    SELECT\n      fi.item ->> 'Name' AS NAME,\n      ROUND((CombinedData.DATA ->> 'CurrentPotential') :: NUMERIC / 100.0, -- 保持 NUMERIC 类型\n        1) AS current_potential\n    FROM\n      CombinedData\n      CROSS JOIN LATERAL jsonb_array_elements (DATA -> 'FuelInventory') AS fi (item)\n    WHERE\n      metric = 'generators'\n      AND fi.item ->> 'Name' IS NOT NULL\n  ),\n itemcost AS (\n    SELECT item_name AS NAME, COST :: NUMERIC -- 显式转换为 NUMERIC\n    FROM item_data\n   ),\n fadianji AS(\n   SELECT COALESCE\n      (p.NAME, i.NAME) AS NAME,\n      ROUND(\n        CASE\n          WHEN SUM(2.5 * COALESCE (i.COST, 0)) IS NOT NULL THEN\n            CAST (\n              SUM(2.5 * COALESCE (i.COST, 0)) AS NUMERIC -- 显式转换为 NUMERIC\n            )\n          ELSE\n            0\n        END,\n        1\n      ) AS zuidaxiaohao\n  FROM CurrentPotential p LEFT JOIN itemcost i USING (NAME)\n  WHERE p.NAME = i.NAME\n  GROUP BY\n    1\n)\nSELECT COALESCE\n  (P.NAME, C.NAME,f.NAME) AS \"物品\",\n  ROUND(COALESCE (P.rate, 0),1) AS \"理论最大生产量\",\n  ROUND(COALESCE (f.zuidaxiaohao, 0) + COALESCE (C.rate, 0), 1) AS \"理论最大消耗量\",\n  ROUND(COALESCE (P.rate, 0),1) - ROUND(COALESCE (f.zuidaxiaohao, 0) + COALESCE (C.rate, 0), 1) AS \"理论最大盈余\"\nFROM\n  production P\n  FULL OUTER JOIN consumption C USING (NAME)\n  FULL OUTER JOIN fadianji f USING (NAME)\nORDER BY\n  \"理论最大盈余\" ASC,\n  \"理论最大消耗量\""
    }
   ]
  },
  { "title": "信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "按地区计算的工厂产量计算器",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "按地区计算工厂产量\n\n通过一个由变量界定的正方形区域，计算输入和输出。\n\n编辑显示的地图并检查建筑物，以获取大约的x + y坐标。然后输入x和y的边界值。工厂的出口（+/-分钟）和进口（-/-分钟）将根据新的区域进行更新。\n\nx最小值，x最大值，y最小值和y最大值是游戏内的坐标。"
   }
  },
  { "title": "工厂详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "工厂地图",
   "type": "geomap",
   "description": "工厂的近似地图——用于绘制工厂边界",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\ndata ->> 'Recipe' as \"配方\",\ndata ->> 'Name' as \"建筑\",\ndata as \"数据\",\n(data -> 'location' ->> 'x')::NUMERIC/100 as \"x坐标\",\n(data -> 'location' ->> 'y')::NUMERIC/100 as \"y坐标\",\n(data -> 'location' ->> 'z')::NUMERIC/100 as \"z坐标\",\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nFROM cache\nwhere metric in ('factory', 'extractor')\nand (data -> 'location' ->> 'x')::NUMERIC/100 >= $xmin\nand (data -> 'location' ->> 'x')::NUMERIC/100 <= $xmax \nand (data -> 'location' ->> 'y')::NUMERIC/100 >= $ymin\nand (data -> 'location' ->> 'y')::NUMERIC/100 <= $ymax\nand url = '$server'\nand session_name = '$session'"
    },
    {
     "rawSql": "SELECT\n  data ->> 'Recipe' as \"配方\",\n  data ->> 'building' as \"建筑\",\n  (data -> 'location' ->> 'x') :: NUMERIC / 100 as \"x坐标\",\n  (data -> 'location' ->> 'y') :: NUMERIC / 100 as \"y坐标\",\n  (data -> 'location' ->> 'z') :: NUMERIC / 100 as \"z坐标\",\n  (\n    ((data -> 'location' ->> 'x') :: NUMERIC + 375000) * 0.0000001015\n  ) as longitude,\n  (\n    ((data -> 'location' ->> 'y') :: NUMERIC + 375000) * -0.0000001172\n  ) as latitude\nFROM\n  cache\nwhere\n  metric in ('factory', 'extractor')\n  and (\n    (data -> 'location' ->> 'x') :: NUMERIC / 100 < $xmin\n    or (data -> 'location' ->> 'x') :: NUMERIC / 100 > $xmax\n    or (data -> 'location' ->> 'y') :: NUMERIC / 100 < $ymin\n    or (data -> 'location' ->> 'y') :: NUMERIC / 100 > $ymax\n  )\n  and url = '$server'\n  and session_name = '$session'"
    },
    {
     "rawSql": "(\n  select\n    id,\n    x,\n    y,\n    ((x * 100 + 375000) * 0.0000001015) as longitude,\n    ((y * 100 + 375000) * -0.0000001172) as latitude\n  from\n    (\n      values\n(1, $xmin, $ymin),\n        (2, $xmax, $ymin),\n        (3, $xmax, $ymax),\n        (4, $xmin, $ymax),\n        (5, $xmin, $ymin)\n    ) as coords (id, x, y)\n)\norder by\n  id"
    }
   ]
  },
  {
   "title": "选中的建筑和配方",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\ndata ->> 'Recipe' as \"配方\",\ndata ->> 'Name' as \"建筑\",\ndata ->> 'ManuSpeed' as \"生产效率\",\ncount(*) as \"总数\"\nFROM cache\nwhere metric in ('factory', 'extractor')\nand (data -> 'location' ->> 'x')::NUMERIC/100 >= $xmin\nand (data -> 'location' ->> 'x')::NUMERIC/100 <= $xmax \nand (data -> 'location' ->> 'y')::NUMERIC/100 >= $ymin\nand (data -> 'location' ->> 'y')::NUMERIC/100 <= $ymax\nand url = '$server'\nand session_name = '$session'\ngroup by \"配方\", \"建筑\", \"生产效率\""
    }
   ]
  }
 ]
}