{
 "title": "电力",
 "description": "幸福工厂数据统计",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "server", "label": "服务器", "query": { "query": "label_values(url)" } },
   {
    "name": "session",
    "label": "会话",
    "query": {
     "query": "label_values({url=\"$server\"},session_name)"
    }
   },
   {
    "name": "circuit",
    "label": "电网",
    "query": {
     "query": "{circuit_id=~\".+\",url=~\"$server\",session_name=~\"$session\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "警告", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "电力警告", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 } },
  { "title": "电网 $circuit 电力", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "保险丝",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fuse_triggered{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "电池组充电百分比",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_percent{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "电池耗尽所需时间",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_seconds_empty{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"} / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "电池差分",
   "type": "timeseries",
   "description": "电池组输入或输出的电量盈余或不足。正值表示给电池充电，负值表示电池放电。",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "battery_differential{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "总电力",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "power_capacity{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "power_max_consumed{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "power_consumed{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "power_production{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "电力差分图",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(vehicle_station_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Truck Stations"
    },
    {
     "expr": "sum(last_over_time(train_station_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Train Stations"
    },
    {
     "expr": "sum(last_over_time(train_power_circuit_consumed{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Trains"
    },
    {
     "expr": "sum(last_over_time(drone_port_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Drone Ports"
    },
    {
     "expr": "sum(last_over_time(factory_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Factory"
    },
    {
     "expr": "sum(last_over_time(resource_sink_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Sinks"
    },
    {
     "expr": "sum(last_over_time(pump_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Pumps"
    },
    {
     "expr": "sum(last_over_time(extractor_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Extractors"
    },
    {
     "expr": "sum(last_over_time(portal_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Portals"
    },
    {
     "expr": "sum(last_over_time(hypertube_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Hypertubes"
    },
    {
     "expr": "sum(last_over_time(fracking_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Resource Well Pressurizers"
    },
    {
     "expression": "$TOTAL-$DRONE-$TRAIN-$TRAIN_STATION-$VEHICLE_STATION-$FACTORY-$SINK-$PUMPS-$EXTRACTORS-$PORTALS-$HYPERTUBES-$RESOURCE_WELLS",
     "type": "math"
    }
   ]
  },
  {
   "title": "电网 $circuit 地图",
   "type": "geomap",
   "description": "显示电网 $circuit 的运行地图",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\ndata ->> 'Name' as \"建筑\",\ndata ->'PowerInfo' ->> 'CircuitGroupID' as \"电网\",\ndata ->> 'Recipe' as \"配方\",\n(data -> 'location' ->> 'x')::NUMERIC/100 as \"x坐标\",\n(data -> 'location' ->> 'y')::NUMERIC/100 as \"y坐标\",\n(data -> 'location' ->> 'z')::NUMERIC/100 as \"z坐标\",\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache where metric in ('factory', 'extractor')\nand (data -> 'PowerInfo' ->> 'CircuitGroupID')::numeric = $circuit\nand url = '$server'\nand session_name = '$session'"
    }
   ]
  },
  {
   "title": "电网和建筑总数",
   "type": "table",
   "description": "每个电网的建筑物数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "select \ndata -> 'PowerInfo' ->> 'CircuitGroupID' as \"电网\",\ncount(*) as \"建筑总数\"\nfrom cache where metric in ('factory', 'extractor')\nand url = '$server'\nand session_name = '$session'\ngroup by \"电网\"\norder by \"建筑总数\""
    }
   ]
  },
  { "title": "电网 $circuit 电力分解图", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "工厂电力图",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "factory_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "factory_power_max{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "卡车站耗电",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "vehicle_station_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "vehicle_station_power_max{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "火车站耗电",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "train_station_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "train_station_power_max{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "火车耗电",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "train_power_circuit_consumed{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "train_power_circuit_consumed_max{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}