{
 "title": "总产品生产",
 "description": "幸福工厂数据统计",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "server", "label": "服务器", "query": { "query": "label_values(url)" } },
   {
    "name": "session",
    "label": "会话",
    "query": {
     "query": "label_values({url=\"$server\"},session_name)"
    }
   },
   { "name": "item", "label": "物品", "query": { "query": "label_values(item_name)" } }
  ]
 },
 "panels": [
  { "title": "报警", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "产品警告", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 } },
  { "title": "物品产量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "实际物品产量",
   "type": "table",
   "description": "实际产量",
   "gridPos": { "h": 47, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH consumption AS (\n  SELECT\n    ingredient ->> 'Name' AS NAME,\n    ROUND(SUM(CASE WHEN ingredient ->> 'CurrentConsumed' ~ '^\\-?\\d+(\\.\\d+)?$' THEN (ingredient ->> 'CurrentConsumed') :: NUMERIC ELSE 0 END), 3) AS rate\n  FROM\n    CACHE CROSS JOIN LATERAL jsonb_array_elements (DATA -> 'ingredients') AS ingredient\n  WHERE\n    metric IN ('factory', 'extractor')\n    AND ingredient ->> 'Name' IS NOT NULL\n    AND ingredient ->> 'Name' != 'Unassigned'\n    AND url = '$server'\n    AND session_name = '$session'\n  GROUP BY\n    1\n),\nproduction AS (\n  SELECT\n    ingredient ->> 'Name' AS NAME,\n    ROUND(SUM(CASE WHEN ingredient ->> 'CurrentProd' ~ '^\\-?\\d+(\\.\\d+)?$' THEN (ingredient ->> 'CurrentProd') :: NUMERIC ELSE 0 END), 3) AS rate\n  FROM\n    CACHE CROSS JOIN LATERAL jsonb_array_elements (DATA -> 'production') AS ingredient\n  WHERE\n    metric IN ('factory', 'extractor')\n    AND ingredient ->> 'Name' IS NOT NULL\n    AND ingredient ->> 'Name' != 'Unassigned'\n    AND url = '$server'\n    AND session_name = '$session'\n  GROUP BY\n    1\n) SELECT COALESCE\n  (P.NAME, C.NAME) AS \"物品\",\n  ROUND(COALESCE (P.rate, 0) - COALESCE (C.rate, 0), 3) AS \"数量\"\nFROM\n  production\n  P FULL OUTER JOIN consumption C USING (NAME)\nORDER BY\n  \"数量\" ASC,\n  \"物品\""
    }
   ]
  },
  {
   "title": "理论生产量",
   "type": "table",
   "description": "最大理论生产量",
   "gridPos": { "h": 47, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH consumption AS (\n  SELECT\n    ingredient ->> 'Name' AS NAME,\n    ROUND(SUM(CASE WHEN ingredient ->> 'MaxConsumed' ~ '^\\-?\\d+(\\.\\d+)?$' THEN (ingredient ->> 'MaxConsumed') :: NUMERIC ELSE 0 END), 3) AS rate\n  FROM\n    CACHE CROSS JOIN LATERAL jsonb_array_elements (DATA -> 'ingredients') AS ingredient\n  WHERE\n    metric IN ('factory', 'extractor')\n    AND ingredient ->> 'Name' IS NOT NULL\n    AND ingredient ->> 'Name' != 'Unassigned'\n    AND url = '$server'\n    AND session_name = '$session'\n  GROUP BY\n    1\n),\nproduction AS (\n  SELECT\n    ingredient ->> 'Name' AS NAME,\n    ROUND(SUM(CASE WHEN ingredient ->> 'MaxProd' ~ '^\\-?\\d+(\\.\\d+)?$' THEN (ingredient ->> 'MaxProd') :: NUMERIC ELSE 0 END), 3) AS rate\n  FROM\n    CACHE CROSS JOIN LATERAL jsonb_array_elements (DATA -> 'production') AS ingredient\n  WHERE\n    metric IN ('factory', 'extractor')\n    AND ingredient ->> 'Name' IS NOT NULL\n    AND ingredient ->> 'Name' != 'Unassigned'\n    AND url = '$server'\n    AND session_name = '$session'\n  GROUP BY\n    1\n) SELECT COALESCE\n  (P.NAME, C.NAME) AS \"物品\",\n  ROUND(COALESCE (P.rate, 0) - COALESCE (C.rate, 0), 3) AS \"数量\"\nFROM\n  production\n  P FULL OUTER JOIN consumption C USING (NAME)\nORDER BY\n  \"数量\" ASC,\n  \"物品\""
    }
   ]
  },
  { "title": "$item 产量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "生产 vs 消耗 /min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "item_production_capacity_per_min{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "items_produced_per_min{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "item_consumption_capacity_per_min{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "items_consumed_per_min{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "生产效率 VS 消耗效率 %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "item_production_capacity_pc{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "item_consumption_capacity_pc{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "优惠劵资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "积分点总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "rate(resource_sink_total_points{url=\"$server\", session_name=\"$session\"}[$__rate_interval]) * 60",
     "legendFormat": "{{sink_type}}"
    }
   ]
  },
  {
   "title": "下一张优惠券的积分点",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 12, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resource_sink_points_to_coupon{url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{sink_type}}"
    }
   ]
  },
  {
   "title": "资源回收器里的优惠券数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resource_sink_collected_coupons{url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "下一张优惠券进度",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resource_sink_percent{url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{sink_type}}"
    }
   ]
  }
 ]
}