groups:
  - name: 电力
    rules:
# record power consumped with 20% margin of overhead
    - record: power_consumed_overhead:min6h
      expr: min(1.2 * max_over_time(power_consumed[6h])) by (circuit_id,url,session_name)
    - record: power_consumed_overhead_or_max_consumed:min6h
      expr: max(power_consumed_overhead:min6h < power_consumed_overhead:min6h or last_over_time(power_max_consumed[1h])) by (circuit_id,url,session_name)
    - record: battery_minutes_empty
      expr: round(battery_seconds_empty/60)

    - alert: 保险丝触发
      expr: fuse_triggered > 0
      labels:
        category: 电力
      annotations:
        summary: "保险丝触发"
        description: 保险丝触发 - 电路 {{ $labels.circuit_id }} 断电。
    - alert: 电池耗尽
      expr: 0 < battery_minutes_empty and battery_minutes_empty < 1800
      for: 10s
      labels:
        category: 电力
      annotations:
        summary: "电池快耗尽"
        description: 电路 {{ $labels.circuit_id }} 的电池电量几乎耗尽，剩余约 {{ $value }} 分钟的电力。
    - alert: 电池耗尽
      expr: battery_differential < 0
      for: 10s
      labels:
        category: 电力
      annotations:
        summary: "电池开始耗电"
        description: 电路 {{ $labels.circuit_id }} 上的电池开始耗电。

# Alert when consumption is *likely* to overtake power capacity - when both max consumption and observed consumption -- with a 20% capacity margin is over power capacity
    - alert: 最大消耗
      expr: power_capacity < power_consumed_overhead_or_max_consumed:min6h
      for: 10s
      labels:
        category: 电力
      annotations:
        summary: "最大消耗过高"
        description: 在电网 {{ $labels.circuit_id }} 上的最大消耗已超过生产量。可能会出现电力不稳定的情况。
